Classes
TaiwoEnoch/OOP_library pull request #1
Opened 2023-05-29 23:02 UTC by TaiwoEnoch

## I create this PR to feature adding classes of OOP school library through the below requirement

- [ ] Create class Person with the following:

- Instance vars: @id, @name, and @age.
- Constructor with name, age, and parent_permission as parameter. name and parent_permission are optional and have default values of "Unknown" and true.
- Getters for @id, @name, and @age.
- Setters for @name and @age.
- Private method of_age? that returns true if @age is greater or equal to 18 and false otherwise.
- Public method can_use_services? that returns true if person is of age or if they have permission from parents.

- [ ] Create class Student with the following:

- Inherits from Person.
- Constructor extends parent's constructor by adding @classroom and a parameter for it.
- Method play_hooky that returns "¯\(ツ)/¯".

- [ ] Create class Teacher with the following:

- Inherits from Person.
- Constructor extends parent's constructor by adding @specialization and a parameter for it.
- Override can_use_services? so it always returns true.
- Each class should be saved in a separate file.

2023-05-29 23:12 UTC, codecaiine commented
hi @TaiwoEnoch Can you go on slack I sent you a message there

2023-05-29 23:25 UTC, codecaiine requested changes
Hi @TaiwoEnoch , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has not completed the readme. Please make sure that all readme header sections are present. Also, you submit another activity . Please make sure to submit your project to correct place 👍  

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-29 23:52 UTC, Owusu-Desmond requested changes
Hi @TaiwoEnoch , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
📌 No Linters error ✅
📌 Great working on the setup of the project ✅
📌 Good commit messages ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-29 23:52 UTC, Owusu-Desmond commented on person.rb
> +
- [ ] Please from the project requirement, You should set both Setters and Getters for @name and @age so I think you should use the attr_accessor for the `:name` and `:age` instance variables. :pray:

2023-05-29 23:52 UTC, Owusu-Desmond commented on person.rb
> +    @id = id
- [ ] Please from the project requirement, it wasn't mentioned that the constructor method should make the `id` instance variable as a parameter of the constructor so I think you should use `Random.rand(1..1000)` to automatically generate an `id` :+1:

2023-05-29 23:52 UTC, Owusu-Desmond commented on README.md
>  The OOP School Library: a coding haven for aspiring programmers. Explore a vast collection of programming books, digital resources, and collaborative coding spaces. Unleash your potential, master OOP
- [ ] You already have this project description in this your readme file so I think that you remove this. :blush:

2023-05-30 00:18 UTC, ridwanediallo approved these changes
# STATUS: APPROVED 🟢
## Hi @TaiwoEnoch , 
![Congratulations!GIF](https://user-images.githubusercontent.com/55918904/191301390-43d62dfa-bfdc-49c5-943b-4d72f4ea5bb8.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used GitHub flow correctly. ✔
- Well done implementing the requested changes by the previous reviewer.  🎉 🎉 🎉 ✔

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-30 00:18 UTC, ridwanediallo commented on person.rb
> +  attr_accessor :id, :name, :age
- [**OPTIONAL**] We should only be able to read the `id` but not modify it. So I would highly recommend you to set it with the `attr_reader`  like this `attr_reader :id ` and just set the name and the age with `attr_accessor` because it allows us to read and at the same time modify a variable.

2023-06-02 11:23 UTC, merged